version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: '${POSTGRES_HOST}'
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mars_network

  nextjs:
    build: .
    container_name: mars_project_nextjs
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    env_file:
      - .env
    networks:
      - mars_network
    volumes:
      - .:/app
      - /app/node_modules # Avoid overwriting node_modules

networks:
  mars_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
