# Use the latest Node.js LTS version as base
FROM node:20-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Copy the entire source code
COPY . .

# Build the app for production
RUN yarn build

# Expose the production port (3003)
EXPOSE 3003

# Start the Next.js app in production mode
CMD ["yarn", "start"]
