version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: '${POSTGRES_HOST_DEV}'
    restart: always
    env_file:
      - .env.local
    environment:
      POSTGRES_USER: '${POSTGRES_USER}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD}'
      POSTGRES_DB: '${POSTGRES_DB}'
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mars_network

  nextjs:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: mars_project_nextjs_dev
    restart: always
    ports:
      - '3003:3003'
    depends_on:
      - postgres
    env_file:
      - .env.local
    environment:
      NODE_ENV: 'development'
      NEXT_PUBLIC_SERVER_PORT: '${NEXT_PUBLIC_SERVER_PORT}'
      NEXT_PUBLIC_SERVER_HOST: '${NEXT_PUBLIC_SERVER_HOST}'
      NEXT_PUBLIC_GOOGLE_CLIENT_ID: '${NEXT_PUBLIC_GOOGLE_CLIENT_ID}'
      NEXT_PUBLIC_GOOGLE_CLIENT_SECRET: '${NEXT_PUBLIC_GOOGLE_CLIENT_SECRET}'
      NEXT_PUBLIC_NASA_API_URL: '${NEXT_PUBLIC_NASA_API_URL}'
      NEXT_PUBLIC_NASA_API_KEY: '${NEXT_PUBLIC_NASA_API_KEY}'
      NEXTAUTH_URL: '${NEXTAUTH_URL}'
      NEXTAUTH_URL_INTERNAL: '${NEXTAUTH_URL_INTERNAL}'
    networks:
      - mars_network
    volumes:
      - .:/app
      - /app/node_modules

networks:
  mars_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
